In [1]:
import pandas as pd

In [2]:
# Save and read data files
nuts = "nuts_df.csv"

nuts_df = pd.read_csv(nuts)

nuts_df

,Unnamed: 0,name_brand,industry_name,report_number,consumer_gender,date_created,reactions,Year,0,1,...,64,65,66,67,68,69,70,diarrhea?,death?,hospitalization?
0,6,MARIANI SLICED ALMONDS,Nuts/Edible Seed,105407,Female,2008-08-01,"['DIARRHEA', 'VOMITING']",2008,'DIARRHEA','VOMITING',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
1,12,JIF CREAMY PEANUT BUTTER,Nuts/Edible Seed,109955,Female,2009-01-21,"['ABDOMINAL PAIN', 'ABDOMINAL PAIN UPPER', 'BO...",2009,'ABDOMINAL PAIN','ABDOMINAL PAIN UPPER',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
2,26,ALNAHKA HALWA WITH PISTACHIOS,Nuts/Edible Seed,106674,Male,2008-09-25,['MOUTH INJURY'],2008,'MOUTH INJURY',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
3,31,NATURAL CHOICES PEANUT BUTTER,Nuts/Edible Seed,110185,Female,2009-02-04,"['ASTHENIA', 'DIARRHEA', 'FATIGUE', 'MALAISE',...",2009,'ASTHENIA','DIARRHEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
4,36,MARGARET HOLMES GREEN BOILED PEANUTS,Nuts/Edible Seed,120918,Male,2009-12-01,['VOMITING'],2009,'VOMITING',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5423,206081,PETER PAN CREAMY PEANUT BUTTER,Nuts/Edible Seed,95925,Female,2007-02-23,"['ABDOMINAL DISCOMFORT', 'ANAEMIA', 'CARDIAC F...",2007,'ABDOMINAL DISCOMFORT','ANAEMIA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False
5424,206083,PLANTERS PEANUTS DRY ROASTED UNSALTED,Nuts/Edible Seed,98126,Male,2007-08-16,"['DYSGEUSIA', 'ORAL PAIN']",2007,'DYSGEUSIA','ORAL PAIN',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
5425,206112,TRADER JOE'S DRY TOASTED PIGNOLIA'S,Nuts/Edible Seed,130676,Female,2010-10-05,"['DYSGEUSIA', 'HYPERSENSITIVITY']",2010,'DYSGEUSIA','HYPERSENSITIVITY',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
5426,206118,PINNEOLA PINE NUTS,Nuts/Edible Seed,134483,NaN,2010-10-20,['DYSGEUSIA'],2010,'DYSGEUSIA',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
5427,206153,AURORA NATURAL PIGNOLIA PINE NUTS,Nuts/Edible Seed,136117,Male,2011-02-25,['DYSGEUSIA'],2011,'DYSGEUSIA',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False

In [4]:
nuts_df['consumer_gender'].value_counts()

consumer_gender
Female          2964
Male            2051
Not Reported       6
Unknown            4
Name: count, dtype: int64

In [3]:
# Save and read data files
peanuts = "peanut_product_df.csv"

peanut_product = pd.read_csv(peanuts)

peanut_product

,Unnamed: 0,name_brand,industry_name,report_number,consumer_gender,date_created,reactions,Year,0,1,...,64,65,66,67,68,69,70,diarrhea?,death?,hospitalization?
0,12,JIF CREAMY PEANUT BUTTER,Nuts/Edible Seed,109955,Female,2009-01-21,"['ABDOMINAL PAIN', 'ABDOMINAL PAIN UPPER', 'BO...",2009,'ABDOMINAL PAIN','ABDOMINAL PAIN UPPER',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
1,31,NATURAL CHOICES PEANUT BUTTER,Nuts/Edible Seed,110185,Female,2009-02-04,"['ASTHENIA', 'DIARRHEA', 'FATIGUE', 'MALAISE',...",2009,'ASTHENIA','DIARRHEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
2,33,PILLSBURY BIG DELUXE PEANUT BUTTER CUP COOKIES,Bakery Prod/Dough/Mix/Icing,111858,Male,2009-01-21,"['ABDOMINAL PAIN', 'DIARRHEA', 'MALAISE', 'VOM...",2009,'ABDOMINAL PAIN','DIARRHEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
3,36,MARGARET HOLMES GREEN BOILED PEANUTS,Nuts/Edible Seed,120918,Male,2009-12-01,['VOMITING'],2009,'VOMITING',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4,83,SKIPPY REDUCED FAT CREAMY PEANUT BUTTER SPREAD,Nuts/Edible Seed,136549,Male,2011-03-07,"['ABDOMINAL PAIN', 'DIARRHEA', 'FEELING OF BOD...",2011,'ABDOMINAL PAIN','DIARRHEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4240,206200,PROTEIN BAR DELUXE - CHOCOLATE PEANUT,Dietary Conventional Foods/Meal Replacements,189623,Female,2015-09-15,"['BLINDNESS TRANSIENT', 'COAGULOPATHY', 'DEHYD...",2015,'BLINDNESS TRANSIENT','COAGULOPATHY',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4241,206260,ADVOBAR MEAL CHOCOLATE PEANUT BUTTER,Choc/Cocoa Prod,197332,Male,2016-04-29,"['BACK PAIN', 'COMPUTERISED TOMOGRAM ABNORMAL'...",2016,'BACK PAIN','COMPUTERISED TOMOGRAM ABNORMAL',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4242,206261,MEAL REPLACEMENT SHAKE PEANUT BUTTER,Dietary Conventional Foods/Meal Replacements,197332,Male,2016-04-29,"['BACK PAIN', 'COMPUTERISED TOMOGRAM ABNORMAL'...",2016,'BACK PAIN','COMPUTERISED TOMOGRAM ABNORMAL',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4243,206269,CRACKER JACKS POPCORN AND PEANUT SNACK FOOD,Snack Food Item,199815,Male,2016-07-29,"['ABDOMINAL DISCOMFORT', 'NAUSEA']",2016,'ABDOMINAL DISCOMFORT','NAUSEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False
4244,206559,LANCE TOASTED CHEESE CRACKERS PEANUT BUTTER,Bakery Prod/Dough/Mix/Icing,210900,Female,2017-04-03,"['ABDOMINAL PAIN', 'DIARRHEA', 'MALAISE', 'MUS...",2017,'ABDOMINAL PAIN','DIARRHEA',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False

In [5]:
peanut_product['consumer_gender'].value_counts()

consumer_gender
Female          2195
Male            1700
Unknown            5
Not Reported       5
Name: count, dtype: int64