In [22]:
import pandas as pd
from pathlib import Path

In [23]:
# File to Load 
food_event_df = Path("food_df.csv")

In [24]:
#Read Food Data File and store into Pandas DataFrames
food_df = pd.read_csv(food_event_df)
food_df.head()

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions
0,SUSPECT,ORE IDA GOLDEN CRINKLES FRENCH FRIES,25,Vegetables/Vegetable Products,100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
1,CONCOMITANT,TYSON FAMILY CHICKEN NUGGETS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
2,CONCOMITANT,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
3,SUSPECT,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,54,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,NaN,NaN,20080325,NaN,"['Other Serious or Important Medical Event', '...",['CEREBROVASCULAR ACCIDENT']
4,SUSPECT,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,54,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,44.0,year(s),Female,20080718,NaN,"['Other Serious or Important Medical Event', '...","['DYSPNOEA', 'FACE OEDEMA', 'HYPERSENSITIVITY'..."

In [35]:
#Value count for Genders affected
total_affected = food_df["consumer_gender"].value_counts()
print(total_affected)

consumer_gender
Female          152916
Male             44243
Unknown             95
Not Reported        42
Name: count, dtype: int64

In [36]:
#Value count for industry Name
foods_affected = food_df["industry_name"].value_counts()
print(foods_affected)

industry_name
Vit/Min/Prot/Unconv Diet(Human/Animal)          84651
Cosmetics                                       78051
Nuts/Edible Seed                                 5428
Vegetables/Vegetable Products                    4489
Soft Drink/Water                                 3330
Bakery Prod/Dough/Mix/Icing                      3309
Fruit/Fruit Prod                                 3039
Fishery/Seafood Prod                             2831
Cereal Prep/Breakfast Food                       2281
Dietary Conventional Foods/Meal Replacements     2233
Milk/Butter/Dried Milk Prod                      1884
Mult Food Dinner/Grav/Sauce/Special              1523
Snack Food Item                                  1426
Baby Food Products                               1408
Coffee/Tea                                       1152
Ice Cream Prod                                   1071
Candy W/O Choc/Special/Chew Gum                  1042
Choc/Cocoa Prod                                   967
Powder Formula                                    592
Prep Salad Prod                                   564
Food Additives (Human Use)                        557
Cheese/Cheese Prod                                512
Whole Grain/Milled Grain Prod/Starch              484
Spices, Flavors And Salts                         448
Dressing/Condiment                                406
Egg/Egg Prod                                      377
Soup                                              340
Food Sweeteners (Nutritive)                       317
Filled Milk/Imit Milk Prod                        312
Meat, Meat Products and Poultry                   306
Macaroni/Noodle Prod                              258
Beverage Bases/Conc/Nectar                        199
Medical Foods, N.E.C.                             176
Vegetable Oils                                    162
Vegetable Protein Prod                            123
Gelatin/Rennet/Pudding Mix/Pie Filling            121
Alcoholic Beverage                                 63
Miscellaneous Food Related Items                   50
Ready to Serve Formula                             41
Color Additiv Food/Drug/Cosmetic                   38
Formula, Form Unspecified                          14
Food Service/Conveyance                            14
Liquid Concentrate Formula                         10
Formula Raw Material                                7
Name: count, dtype: int64

In [37]:
#Value count for industry code
indus_code_affected = food_df["industry_code"].value_counts()
print(indus_code_affected)

industry_code
54     84651
53     78051
23      5428
29      3330
3       3309
24      2911
16      2831
5       2281
41      2233
9       1884
20      1644
25      1578
37      1523
7       1426
40      1408
31      1152
13      1071
21      1067
33      1042
34       967
40P      592
39       564
12       512
45       508
2        484
28       448
27       406
15       377
38       340
22       328
36       317
14       312
17       306
4        258
30       199
41G      176
26       162
18       123
35       121
32        63
52        50
46        49
40N       41
50        38
40C       14
51        14
40O       10
40M        7
Name: count, dtype: int64

In [38]:
role_tag_affected = food_df["role"].value_counts()
print(role_tag_affected)

role
SUSPECT        174737
CONCOMITANT     31869
Name: count, dtype: int64

In [48]:
#Create new dataframe for products that resulted in Death
death_count = food_df['reactions'].str.contains('death').sum()
print(death_count)
death_df = food_df[food_df['reactions'].str.contains('death')]
death_df.head()

159

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions
706,SUSPECT,KRATOM,54,Vit/Min/Prot/Unconv Diet(Human/Animal),2019-CFS-006544,20.0,year(s),Male,20190625,20190601.0,"['Life Threatening', 'Hospitalization', 'Visit...","['Alopecia', 'Apparent death', 'Drug dependenc..."
2598,SUSPECT,SCHIFF MOVE FREE ADVANCE TRIPLE STRENGTH TOTAL...,54,Vit/Min/Prot/Unconv Diet(Human/Animal),171217,NaN,NaN,Female,20131018,NaN,"['Hospitalization', 'Other Serious or Importan...","['Abdominal discomfort', 'Abdominal distension..."
4278,SUSPECT,ONE A DAY MEN'S HEALTH,54,Vit/Min/Prot/Unconv Diet(Human/Animal),2018-CFS-014777,NaN,NaN,Male,20181219,NaN,['Other Serious or Important Medical Event'],"['Apparent death', 'Foreign body']"
4818,SUSPECT,SIMILAC PRO SENSITIVE,40P,Powder Formula,2022-CFS-014372,NaN,NaN,NaN,20220318,NaN,['Death'],"['Death', 'Sudden infant death syndrome']"
6222,CONCOMITANT,Calcium,54,Vit/Min/Prot/Unconv Diet(Human/Animal),2018-CFS-000236,NaN,NaN,Male,20180106,20160530.0,"['Death', 'Hospitalization', 'Disability', 'Vi...","['Asthenia', 'Cognitive disorder', 'Cough', 'C..."

In [49]:
#Create new dataframe for products that resulted in Cancer
cancer_count = food_df['reactions'].str.contains('cancer').sum()
print(cancer_count)
cancer_df = food_df[food_df['reactions'].str.contains('cancer')]
cancer_df.head()

39029

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions
363,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000630,47.0,year(s),Female,20171006,20120627.0,['Other Serious or Important Medical Event'],['Ovarian cancer stage II']
364,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000630,47.0,year(s),Female,20171006,20120627.0,['Other Serious or Important Medical Event'],['Ovarian cancer stage II']
365,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000926,NaN,NaN,Female,20171013,NaN,['Other Serious or Important Medical Event'],['Ovarian cancer']
371,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000196,52.0,year(s),Female,20170921,20141001.0,['Other Serious or Important Medical Event'],"['Ascites', 'Chest pain', 'Dyspnoea', 'Metasta..."
372,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000196,52.0,year(s),Female,20170921,20141001.0,['Other Serious or Important Medical Event'],"['Ascites', 'Chest pain', 'Dyspnoea', 'Metasta..."

In [59]:
#Create new dataframe for products that resulted in Cancer
female_cancer_table = food_df[(food_df['consumer_gender'] == 'Female') & (food_df['reactions'].str.contains('cancer'))]

#female_cancer_df = food_df[food_df['reactions'].str.contains('cancer')]
female_cancer_table.head()

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions
363,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000630,47.0,year(s),Female,20171006,20120627.0,['Other Serious or Important Medical Event'],['Ovarian cancer stage II']
364,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000630,47.0,year(s),Female,20171006,20120627.0,['Other Serious or Important Medical Event'],['Ovarian cancer stage II']
365,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000926,NaN,NaN,Female,20171013,NaN,['Other Serious or Important Medical Event'],['Ovarian cancer']
371,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000196,52.0,year(s),Female,20170921,20141001.0,['Other Serious or Important Medical Event'],"['Ascites', 'Chest pain', 'Dyspnoea', 'Metasta..."
372,SUSPECT,EXEMPTION 4,53,Cosmetics,2017-CFS-000196,52.0,year(s),Female,20170921,20141001.0,['Other Serious or Important Medical Event'],"['Ascites', 'Chest pain', 'Dyspnoea', 'Metasta..."

In [62]:
cancer_count_female = female_cancer_table['reactions'].str.contains('cancer').sum()
print(cancer_count_female)

38436