In [1]:
import json

In [2]:
import pandas as pd

In [3]:
# Save and read data files
food_event_data = "food_df.csv"

food_df = pd.read_csv(food_event_data)

food_df.head()

,role,name_brand,industry_code,industry_name,report_number,consumer.age,consumer.age_unit,consumer.gender,date_created,date_started,outcomes,reactions
0,SUSPECT,ORE IDA GOLDEN CRINKLES FRENCH FRIES,25,Vegetables/Vegetable Products,100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
1,CONCOMITANT,TYSON FAMILY CHICKEN NUGGETS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
2,CONCOMITANT,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."
3,SUSPECT,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,54,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,NaN,NaN,20080325,NaN,"['Other Serious or Important Medical Event', '...",['CEREBROVASCULAR ACCIDENT']
4,SUSPECT,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,54,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,44.0,year(s),Female,20080718,NaN,"['Other Serious or Important Medical Event', '...","['DYSPNOEA', 'FACE OEDEMA', 'HYPERSENSITIVITY'..."

In [4]:
#Check data info.
food_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206606 entries, 0 to 206605
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   role               206606 non-null  object
 1   name_brand         206605 non-null  object
 2   industry_code      206606 non-null  object
 3   industry_name      206606 non-null  object
 4   report_number      206606 non-null  object
 5   consumer.age       138729 non-null  float64
 6   consumer.age_unit  138729 non-null  object
 7   consumer.gender    197296 non-null  object
 8   date_created       206606 non-null  int64
 9   date_started       142088 non-null  float64
 10  outcomes           206606 non-null  object
 11  reactions          206606 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 18.9+ MB

In [5]:
#Rename consumer.age, consumer.age_unit, consumer.gender columns.
food_df = food_df.rename(
    columns={
        'consumer.age':'consumer_age',
        'consumer.age_unit':'consumer_age_unit',
        'consumer.gender':'consumer_gender'})

food_df.head(1)

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions
0,SUSPECT,ORE IDA GOLDEN CRINKLES FRENCH FRIES,25,Vegetables/Vegetable Products,100871,4.0,year(s),Male,20080220,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE..."

In [6]:

# Convert the 'date_started' column to datetime
food_df['date_created'] = pd.to_datetime(food_df['date_created'], format='%Y%m%d')
# Extract the year and create a new column
food_df['Year'] = food_df['date_created'].dt.year
# Assuming 'df' is your DataFrame and 'year' is the column with the year
food_df['Year'] = food_df['Year'].astype(str).str.split('.').str[0].astype(int, errors="ignore")
food_df.head()

,role,name_brand,industry_code,industry_name,report_number,consumer_age,consumer_age_unit,consumer_gender,date_created,date_started,outcomes,reactions,Year
0,SUSPECT,ORE IDA GOLDEN CRINKLES FRENCH FRIES,25,Vegetables/Vegetable Products,100871,4.0,year(s),Male,2008-02-20,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
1,CONCOMITANT,TYSON FAMILY CHICKEN NUGGETS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,2008-02-20,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
2,CONCOMITANT,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,17,"Meat, Meat Products and Poultry",100871,4.0,year(s),Male,2008-02-20,20080220.0,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
3,SUSPECT,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,54,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,NaN,NaN,2008-03-25,NaN,"['Other Serious or Important Medical Event', '...",['CEREBROVASCULAR ACCIDENT'],2008
4,SUSPECT,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,54,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,44.0,year(s),Female,2008-07-18,NaN,"['Other Serious or Important Medical Event', '...","['DYSPNOEA', 'FACE OEDEMA', 'HYPERSENSITIVITY'...",2008

In [7]:
#Search for data to utilize
food_df['consumer_gender'].value_counts()

consumer_gender
Female          152916
Male             44243
Unknown             95
Not Reported        42
Name: count, dtype: int64

In [8]:
food_df['industry_name'].value_counts()

industry_name
Vit/Min/Prot/Unconv Diet(Human/Animal)          84651
Cosmetics                                       78051
Nuts/Edible Seed                                 5428
Vegetables/Vegetable Products                    4489
Soft Drink/Water                                 3330
Bakery Prod/Dough/Mix/Icing                      3309
Fruit/Fruit Prod                                 3039
Fishery/Seafood Prod                             2831
Cereal Prep/Breakfast Food                       2281
Dietary Conventional Foods/Meal Replacements     2233
Milk/Butter/Dried Milk Prod                      1884
Mult Food Dinner/Grav/Sauce/Special              1523
Snack Food Item                                  1426
Baby Food Products                               1408
Coffee/Tea                                       1152
Ice Cream Prod                                   1071
Candy W/O Choc/Special/Chew Gum                  1042
Choc/Cocoa Prod                                   967
Powder Formula                                    592
Prep Salad Prod                                   564
Food Additives (Human Use)                        557
Cheese/Cheese Prod                                512
Whole Grain/Milled Grain Prod/Starch              484
Spices, Flavors And Salts                         448
Dressing/Condiment                                406
Egg/Egg Prod                                      377
Soup                                              340
Food Sweeteners (Nutritive)                       317
Filled Milk/Imit Milk Prod                        312
Meat, Meat Products and Poultry                   306
Macaroni/Noodle Prod                              258
Beverage Bases/Conc/Nectar                        199
Medical Foods, N.E.C.                             176
Vegetable Oils                                    162
Vegetable Protein Prod                            123
Gelatin/Rennet/Pudding Mix/Pie Filling            121
Alcoholic Beverage                                 63
Miscellaneous Food Related Items                   50
Ready to Serve Formula                             41
Color Additiv Food/Drug/Cosmetic                   38
Formula, Form Unspecified                          14
Food Service/Conveyance                            14
Liquid Concentrate Formula                         10
Formula Raw Material                                7
Name: count, dtype: int64

In [9]:
food_df['date_created'].value_counts()

date_created
2017-06-28    3366
2017-06-12    1656
2022-05-23    1125
2017-06-02     974
2017-05-23     970
              ...
2009-07-12       1
2009-11-11       1
2017-10-07       1
2003-10-21       1
2011-08-27       1
Name: count, Length: 6011, dtype: int64

In [10]:
food_df['consumer_age_unit'].value_counts()

consumer_age_unit
year(s)      135551
month(s)       2033
decade(s)       431
day(s)          431
week(s)         283
Name: count, dtype: int64

In [11]:
food_df['role'].value_counts()

role
SUSPECT        174737
CONCOMITANT     31869
Name: count, dtype: int64

In [12]:
# Drop columns not being used for overall project.
report_number_dates_created = food_df.drop(
    columns=[
        'role',
        'industry_code',
        'consumer_age',
        'consumer_age_unit',
        'date_started'
        ])

report_number_dates_created

,name_brand,industry_name,report_number,consumer_gender,date_created,outcomes,reactions,Year
0,ORE IDA GOLDEN CRINKLES FRENCH FRIES,Vegetables/Vegetable Products,100871,Male,2008-02-20,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
1,TYSON FAMILY CHICKEN NUGGETS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
2,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,['Visited a Health Care Provider'],"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008
3,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,2008-03-25,"['Other Serious or Important Medical Event', '...",['CEREBROVASCULAR ACCIDENT'],2008
4,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,Female,2008-07-18,"['Other Serious or Important Medical Event', '...","['DYSPNOEA', 'FACE OEDEMA', 'HYPERSENSITIVITY'...",2008
...,...,...,...,...,...,...,...,...
206601,DULCE DE MARLOW TAMARINDO JELLY,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['Hospitalization', 'Visited Emergency Room', ...","['EMERGENCY CARE EXAMINATION', 'Hospitalizatio...",2004
206602,DULCE DE MARLOW PULPARINDO HOT AND SALTED TAMA...,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['Hospitalization', 'Visited Emergency Room', ...","['EMERGENCY CARE EXAMINATION', 'Hospitalizatio...",2004
206603,GHB-15,Vit/Min/Prot/Unconv Diet(Human/Animal),69899,Male,2004-06-23,['DEATH'],"['DEATH', 'OVERDOSE']",2004
206604,BEEF AND CHEDDAR SANDWICH,Food Service/Conveyance,78526,Male,2005-05-26,['Other Outcome'],"['NAUSEA', 'VOMITING']",2005
206605,BUGLES CORN CHIPS,Snack Food Item,72709,Female,2004-09-08,['Other Outcome'],"['ABDOMINAL PAIN', 'DIARRHEA', 'NAUSEA', 'VOMI...",2004

In [13]:
#Split up the reactions column.
reactions_split_1 = food_df['reactions'].str.split(
    pat="[",
    expand=True)

reactions_split_2 = reactions_split_1[1].str.split(
    pat="]",
    expand=True)

reactions_split = reactions_split_2[0].str.split(
    pat=",",
    expand=True)

reactions_split

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY','HYPERSENSITIVITY','TREMOR','VOMITING',None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY','HYPERSENSITIVITY','TREMOR','VOMITING',None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY','HYPERSENSITIVITY','TREMOR','VOMITING',None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,'CEREBROVASCULAR ACCIDENT',None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,'DYSPNOEA','FACE OEDEMA','HYPERSENSITIVITY','PRURITUS','RASH','RASH MACULAR','SWELLING FACE',None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206601,'EMERGENCY CARE EXAMINATION','Hospitalization','MALAISE','METAL POISONING',None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
206602,'EMERGENCY CARE EXAMINATION','Hospitalization','MALAISE','METAL POISONING',None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
206603,'DEATH','OVERDOSE',None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
206604,'NAUSEA','VOMITING',None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
206605,'ABDOMINAL PAIN','DIARRHEA','NAUSEA','VOMITING',None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [14]:
# Find which rows have the food reaction diarrhea and apply the answer to a column new column.
reactions_split['diarrhea?'] = reactions_split.iloc[:, 0:70].apply(lambda x: x.str.contains('DIARRHEA')).any(axis=1)
reactions_split['death?'] = reactions_split.iloc[:, 0:70].apply(lambda x: x.str.contains('DEATH')).any(axis=1)
reactions_split['hospitalization?'] = reactions_split.iloc[:, 0:70].apply(lambda x: x.str.contains('Hospitalization')).any(axis=1)

In [15]:
# Merge reaction data with revised report.
reactions_detailed = pd.merge(
    report_number_dates_created,
    reactions_split,
    left_index=True,
    right_index=True)

# Drop outcomes column
reactions_detailed = reactions_detailed.drop(columns='outcomes')
reactions_detailed

,name_brand,industry_name,report_number,consumer_gender,date_created,reactions,Year,0,1,2,...,64,65,66,67,68,69,70,diarrhea?,death?,hospitalization?
0,ORE IDA GOLDEN CRINKLES FRENCH FRIES,Vegetables/Vegetable Products,100871,Male,2008-02-20,"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY',...,None,None,None,None,None,None,None,False,False,False
1,TYSON FAMILY CHICKEN NUGGETS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY',...,None,None,None,None,None,None,None,False,False,False
2,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,"['ABDOMINAL PAIN', 'CHILLS', 'DEFAECATION URGE...",2008,'ABDOMINAL PAIN','CHILLS','DEFAECATION URGENCY',...,None,None,None,None,None,None,None,False,False,False
3,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,2008-03-25,['CEREBROVASCULAR ACCIDENT'],2008,'CEREBROVASCULAR ACCIDENT',None,None,...,None,None,None,None,None,None,None,False,False,False
4,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,Female,2008-07-18,"['DYSPNOEA', 'FACE OEDEMA', 'HYPERSENSITIVITY'...",2008,'DYSPNOEA','FACE OEDEMA','HYPERSENSITIVITY',...,None,None,None,None,None,None,None,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206601,DULCE DE MARLOW TAMARINDO JELLY,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['EMERGENCY CARE EXAMINATION', 'Hospitalizatio...",2004,'EMERGENCY CARE EXAMINATION','Hospitalization','MALAISE',...,None,None,None,None,None,None,None,False,False,True
206602,DULCE DE MARLOW PULPARINDO HOT AND SALTED TAMA...,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['EMERGENCY CARE EXAMINATION', 'Hospitalizatio...",2004,'EMERGENCY CARE EXAMINATION','Hospitalization','MALAISE',...,None,None,None,None,None,None,None,False,False,True
206603,GHB-15,Vit/Min/Prot/Unconv Diet(Human/Animal),69899,Male,2004-06-23,"['DEATH', 'OVERDOSE']",2004,'DEATH','OVERDOSE',None,...,None,None,None,None,None,None,None,False,True,False
206604,BEEF AND CHEDDAR SANDWICH,Food Service/Conveyance,78526,Male,2005-05-26,"['NAUSEA', 'VOMITING']",2005,'NAUSEA','VOMITING',None,...,None,None,None,None,None,None,None,False,False,False
206605,BUGLES CORN CHIPS,Snack Food Item,72709,Female,2004-09-08,"['ABDOMINAL PAIN', 'DIARRHEA', 'NAUSEA', 'VOMI...",2004,'ABDOMINAL PAIN','DIARRHEA','NAUSEA',...,None,None,None,None,None,None,None,True,False,False

In [16]:
# Test a search for diarrhea in each column.
test = reactions_detailed.loc[reactions_detailed['diarrhea?'] == True]

test

,name_brand,industry_name,report_number,consumer_gender,date_created,reactions,Year,0,1,2,...,64,65,66,67,68,69,70,diarrhea?,death?,hospitalization?
6,MARIANI SLICED ALMONDS,Nuts/Edible Seed,105407,Female,2008-08-01,"['DIARRHEA', 'VOMITING']",2008,'DIARRHEA','VOMITING',None,...,None,None,None,None,None,None,None,True,False,False
10,FRESH GRAPES,Fruit/Fruit Prod,107148,Male,2008-08-22,"['DIARRHEA', 'MALAISE']",2008,'DIARRHEA','MALAISE',None,...,None,None,None,None,None,None,None,True,False,False
12,JIF CREAMY PEANUT BUTTER,Nuts/Edible Seed,109955,Female,2009-01-21,"['ABDOMINAL PAIN', 'ABDOMINAL PAIN UPPER', 'BO...",2009,'ABDOMINAL PAIN','ABDOMINAL PAIN UPPER','BODY TEMPERATURE INCREASED',...,None,None,None,None,None,None,None,True,False,False
27,SUNNY SEA SMOKED OYSTERS IN TERIYAKI SAUCE,Fishery/Seafood Prod,106984,Female,2008-07-01,"['ABDOMINAL PAIN', 'DIARRHEA', 'HEADACHE', 'VO...",2008,'ABDOMINAL PAIN','DIARRHEA','HEADACHE',...,None,None,None,None,None,None,None,True,False,False
29,"PACE PICANTE SAUCE, MEDIUM",Mult Food Dinner/Grav/Sauce/Special,109428,Female,2008-07-10,"['ABDOMINAL PAIN', 'DIARRHEA', 'GASTROENTERITI...",2008,'ABDOMINAL PAIN','DIARRHEA','GASTROENTERITIS SALMONELLA',...,None,None,None,None,None,None,None,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206532,EXTENZE,Vit/Min/Prot/Unconv Diet(Human/Animal),2023-CFS-006338,Male,2023-06-19,"['DIARRHEA', 'Nausea', 'Pyrexia', 'Tremor', 'V...",2023,'DIARRHEA','Nausea','Pyrexia',...,None,None,None,None,None,None,None,True,False,False
206559,LANCE TOASTED CHEESE CRACKERS PEANUT BUTTER,Bakery Prod/Dough/Mix/Icing,210900,Female,2017-04-03,"['ABDOMINAL PAIN', 'DIARRHEA', 'MALAISE', 'MUS...",2017,'ABDOMINAL PAIN','DIARRHEA','MALAISE',...,None,None,None,None,None,None,None,True,False,False
206565,BOB'S RED MILL TAPIOCA FLOUR STARCH,Whole Grain/Milled Grain Prod/Starch,211749,Female,2017-02-15,"['CARDIAC FIBRILLATION', 'DIARRHEA', 'DIZZINES...",2017,'CARDIAC FIBRILLATION','DIARRHEA','DIZZINESS',...,None,None,None,None,None,None,None,True,False,False
206578,MARKETSIDE CAESAR SALAD KIT,Prep Salad Prod,2022-CFS-000786,NaN,2021-12-10,"['Abdominal pain', 'DIARRHEA', 'Vomiting']",2021,'Abdominal pain','DIARRHEA','Vomiting',...,None,None,None,None,None,None,None,True,False,False
206605,BUGLES CORN CHIPS,Snack Food Item,72709,Female,2004-09-08,"['ABDOMINAL PAIN', 'DIARRHEA', 'NAUSEA', 'VOMI...",2004,'ABDOMINAL PAIN','DIARRHEA','NAUSEA',...,None,None,None,None,None,None,None,True,False,False

In [17]:
# Transport reactions to CSV file.
reactions_detailed.to_csv("Reactions/reactions_detailed.csv")

In [18]:
#Split up the outcomes column.
outcomes_split_1 = food_df['outcomes'].str.split(
    pat="[",
    expand=True)

outcomes_split_2 = outcomes_split_1[1].str.split(
    pat="]",
    expand=True)

outcomes_split = outcomes_split_2[0].str.split(
    pat=",",
    expand=True)

outcomes_split

,0,1,2,3,4,5,6
0,'Visited a Health Care Provider',None,None,None,None,None,None
1,'Visited a Health Care Provider',None,None,None,None,None,None
2,'Visited a Health Care Provider',None,None,None,None,None,None
3,'Other Serious or Important Medical Event','Other Serious Outcome',None,None,None,None,None
4,'Other Serious or Important Medical Event','Visited Emergency Room','Other Serious Outcome',None,None,None,None
...,...,...,...,...,...,...,...
206601,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None
206602,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None
206603,'DEATH',None,None,None,None,None,None
206604,'Other Outcome',None,None,None,None,None,None
206605,'Other Outcome',None,None,None,None,None,None

In [19]:
outcomes_split['death?'] = outcomes_split.iloc[:, 0:70].apply(lambda x: x.str.contains('DEATH')).any(axis=1)
food_df['Year'] = food_df['Year'].astype(str).str.split('.').str[0].astype(int, errors="ignore")
outcomes_split

,0,1,2,3,4,5,6,death?
0,'Visited a Health Care Provider',None,None,None,None,None,None,False
1,'Visited a Health Care Provider',None,None,None,None,None,None,False
2,'Visited a Health Care Provider',None,None,None,None,None,None,False
3,'Other Serious or Important Medical Event','Other Serious Outcome',None,None,None,None,None,False
4,'Other Serious or Important Medical Event','Visited Emergency Room','Other Serious Outcome',None,None,None,None,False
...,...,...,...,...,...,...,...,...
206601,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None,False
206602,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None,False
206603,'DEATH',None,None,None,None,None,None,True
206604,'Other Outcome',None,None,None,None,None,None,False
206605,'Other Outcome',None,None,None,None,None,None,False

In [20]:
test2 = outcomes_split.loc[outcomes_split['death?'] == True]

test2

,0,1,2,3,4,5,6,death?
11,'DEATH','Hospitalization',None,None,None,None,None,True
97,'DEATH','Other Serious or Important Medical Event',None,None,None,None,None,True
176,'DEATH',None,None,None,None,None,None,True
187,'DEATH',None,None,None,None,None,None,True
188,'DEATH','Hospitalization','Required Intervention','Visited Emergency Room',None,None,None,True
...,...,...,...,...,...,...,...,...
206567,'DEATH',None,None,None,None,None,None,True
206574,'DEATH','Other Serious or Important Medical Event',None,None,None,None,None,True
206579,'DEATH',None,None,None,None,None,None,True
206580,'DEATH',None,None,None,None,None,None,True
206603,'DEATH',None,None,None,None,None,None,True

In [21]:
outcomes_detailed = pd.merge(
    report_number_dates_created,
    outcomes_split,
    left_index=True,
    right_index=True)

outcomes_detailed = outcomes_detailed.drop(columns='reactions')
outcomes_detailed

,name_brand,industry_name,report_number,consumer_gender,date_created,outcomes,Year,0,1,2,3,4,5,6,death?
0,ORE IDA GOLDEN CRINKLES FRENCH FRIES,Vegetables/Vegetable Products,100871,Male,2008-02-20,['Visited a Health Care Provider'],2008,'Visited a Health Care Provider',None,None,None,None,None,None,False
1,TYSON FAMILY CHICKEN NUGGETS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,['Visited a Health Care Provider'],2008,'Visited a Health Care Provider',None,None,None,None,None,None,False
2,TYSON BUFFALO STYLE CHICKEN BREAST STRIPS,"Meat, Meat Products and Poultry",100871,Male,2008-02-20,['Visited a Health Care Provider'],2008,'Visited a Health Care Provider',None,None,None,None,None,None,False
3,CENTRUM SILVER MULTIVITAMIN MULTIMINERAL SUPPL...,Vit/Min/Prot/Unconv Diet(Human/Animal),101614,NaN,2008-03-25,"['Other Serious or Important Medical Event', '...",2008,'Other Serious or Important Medical Event','Other Serious Outcome',None,None,None,None,None,False
4,VITAMIN WORLD TRIPLE STRENGTH JOINT SOOTHER,Vit/Min/Prot/Unconv Diet(Human/Animal),104879,Female,2008-07-18,"['Other Serious or Important Medical Event', '...",2008,'Other Serious or Important Medical Event','Visited Emergency Room','Other Serious Outcome',None,None,None,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206601,DULCE DE MARLOW TAMARINDO JELLY,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['Hospitalization', 'Visited Emergency Room', ...",2004,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None,False
206602,DULCE DE MARLOW PULPARINDO HOT AND SALTED TAMA...,Candy W/O Choc/Special/Chew Gum,67673,Male,2004-03-04,"['Hospitalization', 'Visited Emergency Room', ...",2004,'Hospitalization','Visited Emergency Room','Visited a Health Care Provider',None,None,None,None,False
206603,GHB-15,Vit/Min/Prot/Unconv Diet(Human/Animal),69899,Male,2004-06-23,['DEATH'],2004,'DEATH',None,None,None,None,None,None,True
206604,BEEF AND CHEDDAR SANDWICH,Food Service/Conveyance,78526,Male,2005-05-26,['Other Outcome'],2005,'Other Outcome',None,None,None,None,None,None,False
206605,BUGLES CORN CHIPS,Snack Food Item,72709,Female,2004-09-08,['Other Outcome'],2004,'Other Outcome',None,None,None,None,None,None,False

In [22]:
#Transport outcomes to CSV file.

outcomes_detailed.to_csv("outcomes_detailed.csv")

In [23]:
# Filtering out rows to pull data based on name_brand containing the word 'PEANUT' into a CSV.
peanut_product = reactions_detailed[reactions_detailed['name_brand'].str.contains('PEANUT', na=False)]

peanut_product_df = pd.DataFrame(peanut_product)

peanut_product_df.head()

peanut_product_df.to_csv("Nuts/peanut_product_df.csv")

In [24]:
# Filtering out rows to pull data based on industry_name 'Nuts?Edible Seed' into a CSV.
nuts = reactions_detailed.loc[reactions_detailed['industry_name'] == 'Nuts/Edible Seed']

nuts_df = pd.DataFrame(nuts)

nuts_df.head()

nuts_df.to_csv("Nuts/nuts_df.csv")